# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GsRbGKphhBgkS7Ps_qdEP6rVxgv1NrP_
"""

import streamlit as st
import sqlite3
import pandas as pd

st.title("📈 KOSPI Reports DB Viewer")

# DB 연결
conn = sqlite3.connect("kospi_reports.db")

# 테이블 목록 조회
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)
table_list = tables['name'].tolist()

selected_table = st.selectbox("테이블 선택", table_list)

# 선택한 테이블 내용 조회
if selected_table:
    df = pd.read_sql(f"SELECT * FROM {selected_table} LIMIT 100", conn)
    st.write(f"🔍 {selected_table} 테이블 미리보기 (최대 100행)")
    st.dataframe(df)

conn.close()