# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GsRbGKphhBgkS7Ps_qdEP6rVxgv1NrP_
"""

# -*- coding: utf-8 -*-
import streamlit as st
import sqlite3
import pandas as pd

st.title("📈 KOSPI Reports DB Viewer")

# DB 연결
conn = sqlite3.connect("kospi_reports.db")

# 기본 테이블명 지정 (예: 'reports')
table_name = "reports"  # 여기에 실제 테이블 이름을 넣으세요

# 종목명 검색 입력창
search_term = st.text_input("🔎 종목명 검색", "")

# 쿼리 생성
if search_term:
    query = f"""
        SELECT * FROM {table_name}
        WHERE 종목명 LIKE ?
        LIMIT 100
    """
    df = pd.read_sql(query, conn, params=(f"%{search_term}%",))
else:
    query = f"SELECT * FROM {table_name} LIMIT 100"
    df = pd.read_sql(query, conn)

# 결과 출력
st.write(f"📄 {table_name} 테이블 미리보기 (최대 100행)")
st.dataframe(df)

conn.close()
